name: CI - Check current working directory and repo contents

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check current working directory and repo contents
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la

      - name: List all files in the repo
        run: |
          find . -type f
